<a href="https://colab.research.google.com/github/ramses2099/projectpytorch/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSOR MATH OPERATION**


*   Add, Subtract, Multiply, Divide Raminders, Exponents
*   Shorthand and uh, Longhand
*   Reassignment



In [1]:
import torch
import numpy as np

In [6]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])


In [8]:
# Add
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [9]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [11]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [13]:
# Subtraction
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [14]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [15]:
# Multiplication
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [16]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [17]:
# Division
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [19]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [20]:
# Remainder Modulus
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [22]:
# Exponents / Power
tensor_b ** tensor_a

tensor([   5,   36,  343, 4096])

In [23]:
# Exponents
torch.pow(tensor_b, tensor_a)

tensor([   5,   36,  343, 4096])

In [24]:
# Reassignment
tensor_b.add_(tensor_a)
tensor_b

tensor([ 6,  8, 10, 12])