<a href="https://colab.research.google.com/github/ramses2099/projectpytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSORS**


*   A torch. Tensor is a multi-dimensional matrix elements of a single data type.
*   Similar To Numpy Arrays, but full of fun that make them work better on GPUs (vs regular CPU's).
*   Default data type of float32.
*   More suitable for deep learning than a numpy array.





In [3]:
import torch
import numpy as np

# **LISTS**

In [5]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# **NUMPY ARRAY**

In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.00918931, 0.59385827, 0.32599885, 0.82457644],
       [0.83331658, 0.68142388, 0.28643396, 0.41625517],
       [0.73610009, 0.81342266, 0.20552331, 0.69552167]])

# **TENSORS**

In [7]:
tensor_2d = torch.rand(3,4)
tensor_2d

tensor([[0.4078, 0.6768, 0.0681, 0.8614],
        [0.3753, 0.9702, 0.5254, 0.1222],
        [0.8694, 0.6214, 0.4036, 0.4102]])

In [8]:
tensor_3d= torch.rand(2,3,4)
tensor_3d

tensor([[[0.5289, 0.3678, 0.0073, 0.0522],
         [0.8636, 0.4291, 0.7442, 0.5750],
         [0.3167, 0.4830, 0.6527, 0.0397]],

        [[0.1257, 0.5924, 0.7063, 0.5164],
         [0.9898, 0.4028, 0.9651, 0.9835],
         [0.3948, 0.9619, 0.0150, 0.2494]]])

In [9]:
# Create tensor out of numpy array
my_tesonr = torch.from_numpy(np1)
my_tesonr

tensor([[0.0092, 0.5939, 0.3260, 0.8246],
        [0.8333, 0.6814, 0.2864, 0.4163],
        [0.7361, 0.8134, 0.2055, 0.6955]], dtype=torch.float64)