<a href="https://colab.research.google.com/github/ramses2099/projectpytorch/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_tensor = torch.arange(0,10)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Reshape and view
my_tensor= my_tensor.reshape(2,5)
my_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
# Reshape if we don't know the number of items using -1
my_tensor2 = torch.arange(10)
my_tensor2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
my_tensor2 = my_tensor2.reshape(2,-1)
my_tensor2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
my_tensor3 = torch.arange(10)
my_tensor3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
my_tensor4 = my_tensor3.view(2,5)
my_tensor4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
# with reshepa and view, they wil update
my_tensor5 = torch.arange(10)
my_tensor5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_tensor6 = my_tensor5.reshape(2,5)
my_tensor6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
my_tensor5[1] = 10
my_tensor5

tensor([ 0, 10,  2,  3,  4, 10, 10, 10, 10, 10])

In [16]:
my_tensor6


tensor([[ 0, 10,  2,  3,  4],
        [10, 10, 10, 10, 10]])

In [17]:
# Slices
my_tensor7 = torch.arange(10)
my_tensor7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# Grab especific item
my_tensor7[7]

tensor(7)

In [21]:
# Slices
my_tensor7[1:4]

tensor([1, 2, 3])